language: go

matrix:
  include:
  - go: 1.11.x
  - go: 1.12.x
    env: LATEST=true
  - go: tip
  allow_failures:
  - go: tip

script:
- go vet ./...
- go test -v -race ./...

notifications:
  slack:
    rooms:
      secure: P+giufRg/5r8UtXik+FZ16De063gFs61c9fpqd6pp6KQ9jhBIOjStykVSKRF8fztUWkToy3p1/j6b9PR1Hu8ZmYFGJgOvV6x0h4Una2Bwa4MipWVOQOliU++Zp0VYy/UXlSdKzASeQRp5l0BHVUm+ieZZF9yW7rwhXaD3QqSayCThCdZ9D1hltub1/L6v7FIqn9EJER17LllkV9oyS899sWbNcOn+T2/jOZAhkTszE7y17L3VZYJ470jSgqILpA2jdvTvLknpFJNGj+slLuW0c+U4Zg90NZFngOdPTK3pG80MdaM67otlOYDg/dqGau/VMeTSJEKzuEXCkSPEwhEVjwz/X8O/+2/lc3XJaPlLmwy6gUJK0vEhoJSmO+DICZczto/ngnFiY82TkJwkLVz+wSVVSTPE2Q1AsWvZNbYhm6B21fBfmsY/57MkXtqNfknPeUBJeCfGSzqfilUIF3aL8L/9C2417PPXCzYq7X23392Bp7bLzu/iGLayngM0LggwSLKp36+50ctm8w36VqVpug03XHg9oFd2Q0FdeKwe6MIjLiuvFVmSVqlQkP6cZDhlc3UT/8r/AGEF4YCi9NxPcdz01RcmWXoBPcZ//dRAF12Xro5xLXt1yFqx+puvVeQLFEE+YQiAASoNe4kX0qqGHgHVng9s2bfhNysDhNGCy8=
